export const SET_COMMENTS_LOADING = 'SET_COMMENTS_LOADING';
export const SET_POSTS_LOADING = 'SET_POSTS_LOADING';
export const SET_POSTS = 'SET_POSTS';
export const ADD_POSTS = 'ADD_POSTS';
export const POSTS_OPERATION_FAILURE = 'POSTS_OPERATION_FAILURE';
export const COMMENTS_OPERATION_FAILURE = 'COMMENTS_OPERATION_FAILURE';
export const SET_COMMENTS = 'SET_COMMENTS';
export const ADD_COMMENTS = 'ADD_COMMENTS';
